[package]
name = "hl7-tools"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.5", features = ["neovim-0-10"] }
hl7-parser = { path = "../hl7-parser", features = ["chrono"] }
chrono = { version = "0.4" }

